### ISSUE TITLE
Lua runtime error in line 541, Aegisub-Motion v1.0.2

### ISSUE THREAD

**Issue by Pin14** [TypesettingTools/Aegisub-Motion#28]
![image](https://cloud.githubusercontent.com/assets/12600433/7801436/e0229d1a-0324-11e5-8a0b-44e5b2502d49.png)
I can apply with the Beta2. Beta3/4... doesen't work (different lua errors)
![image](https://cloud.githubusercontent.com/assets/12600433/7801464/450741f4-0325-11e5-8fc3-c45b7c55cc15.png)
This is my version. (Aegisub x64 is up to date and the os is win 8.1 x64)

**Comment by torque** [comment]
This is a bug that occurs sometimes when you're trying to apply tracking data to the last line in a file. I've known about it for a while but haven't gotten around to fixing it. It should go away if you add a blank line after your tracking section.

I'll leave this open until I actually get it fixed.

**Comment by torque** [comment]
Just pushed the update that should fix this. Let me know if you still have problems.

**Comment by Pin14** [comment]
It's fixed :) thank you
