### ISSUE TITLE
Lua reported a runtime error

### ISSUE THREAD

**Issue by OmAn94** [TypesettingTools/Aegisub-Motion#29]
Hello, first of all, I have aegisub 3.2.2 at 32 bits, and aegisub motion v1.0.4, I erase all and install that versions, since the new update was released I have this problem.

Lua reported a runtime error: File &quot;C:/Program Files (x86)\Aegisub\automation\autoload\a-mo.Aegisub-Motion.moon&quot;, line 536 File &quot;C:/Program Files (x86)\Aegisub\automation\include\a-mo\MotionHandler.moon&quot;, line 112 applyMotion File &quot;C:/Program Files (x86)\Aegisub\automation\include\a-mo\MotionHandler.moon&quot;, line 172 method File &quot;&quot;, line -1 ? File &quot;C:/Program Files (x86)\Aegisub\automation\include\a-mo\MotionHandler.moon&quot;, line 176 attempt to perform arithmetic on local &apos;t1&apos; (a nil value)

I'm new in this, so I need help....and I want to learn more. See ya.

**Comment by torque** [comment]
Somewhere in the lines you're trying to track, you have a `\fade` tag where you should have a `\fad` tag. Unfortunately the error handling of this isn't very good at the moment, and I need to improve it.

**Comment by OmAn94** [comment]
So if I try to change the tag \fade by \fad, the error will still apear? Or there's nothing I  can do? Thanks for answer so quickly.

**Comment by torque** [comment]
To clarify, ASS has two tags to control fading a line, [`\fad`](http://docs.aegisub.org/3.2/ASS_Tags/#\\fad) and [`\fade`](http://docs.aegisub.org/3.2/ASS_Tags/#\\fade). This bug occurs when you have a tag of the syntax `\fade(timein,timeout)`, which should be `\fad(timein,timeout)`. It will also happen with a variety of other malformed `\fade` tags, but this is probably the most common.

**Comment by torque** [comment]
This issue was addressed with commits 8e5fbe068bd8f8f53b3cc708f1f72baa51cfda01  and 6c2e1b74274dbe3c19acfdbf821ca229d3dd2c73. I'm closing it, but I'm not sure when I'll make a new release bundle.
