### ISSUE TITLE
Error in with motion tracking script

### ISSUE THREAD

**Issue by nighthwk** [TypesettingTools/Aegisub-Motion#35]
So I already typed in the directory for the encoder binary, but when i click "Write Local" I get this error message:

http://i.imgur.com/a/PZ9GU

What write permission exactly?

**Comment by torque** [comment]
This error message does not appear in the current Aegisub-Motion source anywhere, which I suspect indicates that you are using a very old version. I recommend updating. The best method of installation currently is through [DependencyControl](https://github.com/TypesettingTools/DependencyControl). I should also update the pre-packaged zip release now that development is stalled.
