### ISSUE TITLE
trim error

### ISSUE THREAD

**Issue by mojie126** [TypesettingTools/Aegisub-Motion#38]
Encoding error:
﻿x264_64_tMod-8bit-all.exe : mp4 [info]: audio muxing feature is disabled.
所在位置 行:1 字符: 2
+ & <<<<  "E:\x264_64_tMod-8bit-all.exe" --crf 16 --tune fastdecode -i 250 --fps 23.976 --sar 1:1 --index "E:
\mocha-TEMP/123.index" --seek 1227 --frames 85 -o "E:\mocha-TEMP/123[1227-1311].mp4" "F:\taikonglvke/123.avs"
 2>&1 | Out-File C:\Users\ADMINI~1\AppData\Local\Temp\a-mo.encode.log -en UTF8; if($LASTEXITCODE -ne 0) {echo
 "If there is no log before this, your encoder is not a working executable or your encoding command is invali
d." | ac -en utf8 C:\Users\ADMINI~1\AppData\Local\Temp\a-mo.encode.log; exit 1}; exit 0
    + CategoryInfo          : NotSpecified: (mp4 [info]: aud...re is disabled.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
avs [error]: Cannot load file 'D:/MarukoToolbox/tools/avs/plugins/LSMASHSource.DLL'.
(F:\taikonglvke/123.avs, line 1)
x264 [error]: could not open input file `F:\taikonglvke/123.avs'
mp4 [error]: failed to finish movie.

If there is no log before this, your encoder is not a working executable or your encoding command is invalid.

**Comment by torque** [comment]
This is error is being caused by avisynth.

I guess you are using the AVS video provider in Aegisub? (preferences -> advanced -> video -> Video provider). If so, you somehow have a broken avisynth configuration (avs is failing to load your source plugin).

I'm going to say this isn't a strictly supported setup either, because I have no way to test it. If possible, use the FFMpegSource2 video provider.

**Comment by line0** [comment]
My first guess is a possible platform mismatch. 
Make sure your local AviSynth install and L-SMASH are either both 64-bit or both 32-bit.
Do note that Aegisub ships with its own copy of AviSynth, which is *not* used for a-mo trimming.

**Comment by mojie126** [comment]
Well, I see. Thank you

**Comment by line0** [comment]
@mojie126 could you resolve your issue?

**Comment by KyawKhantte** [comment]
Encoding error:
﻿x264.exe : C:\Users\User\Downloads\Programs\x264.exe: unknown option -- s
At line:1 char:38
+ ... er\Videos"; & "C:\Users\User\Downloads\Programs\x264.exe" -ss 0 -an - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\User\D...own option -- s:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
If there is no log before this, your encoder is not a working executable or your encoding command is invalid.
