### ISSUE TITLE
"Aegisub thinks your video is 0 frames long"

### ISSUE THREAD

**Issue by tcclives23** [TypesettingTools/Aegisub-Motion#52]
Ok, let me preface this by saying that I am very much a noob when it comes to all things typesetting so I'm not sure if it's a bug or if it's something I've done wrong. Probably the latter. In any case, when I try to trim any file on any line I get this error:

![Screenshot 2020-06-19 09 42 34](https://user-images.githubusercontent.com/67153629/85138667-2ac58f80-b211-11ea-885f-37fed069a273.png)

System info:
![Screenshot 2020-06-19 09 46 06](https://user-images.githubusercontent.com/67153629/85138973-b8a17a80-b211-11ea-8f30-c2225d7211ea.png)

Log (I think):
[Log.txt](https://github.com/TypesettingTools/Aegisub-Motion/files/4804924/Log.txt)

Aegisub version:
[Aegisub Version.txt](https://github.com/TypesettingTools/Aegisub-Motion/files/4804928/Aegisub.Version.txt)

File and ASS file I import into Aegisub (Although, like I said it's ANY file I use):
[Mega](https://mega.nz/folder/r1Ew2AqJ#WuSANBTIPFT-JigNypVB5g)

Any help would be greatly appreciated. Please let me know if there's any more info I should provide.  Thank you!

**Comment by SchRita** [comment]
Hi, did you use a tutorial for starting out with Aegisub-Motion?

**Comment by tcclives23** [comment]
A few plus numerous youtube videos.

[https://subarashii-no-fansub.github.io/Subbing-Tutorial/Tracking-Motion/](https://subarashii-no-fansub.github.io/Subbing-Tutorial/Tracking-Motion/)
[https://unanimated.github.io/ts/index.htm](https://unanimated.github.io/ts/index.htm)

 If you have any other tutorial suggestions? I could use them all!
